---
title: "ALT_analysis"
output: html_document
date: "2023-12-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# 检查是否已安装 pacman
if (!requireNamespace("pacman", quietly = TRUE)) {
  install.packages("pacman") }   # 如果未安装，则安装包
#install.packages("cowplot")
# 加载所需要的R包
pacman::p_load("tidyverse","bruceR","ggplot2","ggridges","psych","psychTools","DataExplorer","patchwork","cowplot","ggpubr","BayesFactor","careless","rticles"," xaringan","igraph")
source("R_rainclouds.R")
```

# ALT1 
## ALT1 每个被试的反应时和正确率的记录
```{r 按匹配与不匹配绘制acc和RT}
ALT1_data <- ALT1_all%>%mutate(ID = as.character(ID)) %>%
   mutate(ParticipantID = as.character(ParticipantID)) %>%
  mutate(rt=as.numeric(rt))%>% #转变被试编号和反应时类型为字符型与数值型
  mutate(correct = ifelse(correct == "true", 1, ifelse(correct == "false", 0, NA)))%>% ##重编码correct，1对0错
  filter(screen_id%in%c("formal_ALT1_1","formal_ALT1_2") )%>% #选择正式实验的数据
  group_by(ID,conditionType,condition) %>%  #按被试与条件分组
  summarise(
    avg_rt = mean(rt, na.rm = TRUE),#每个被试在类似"circle_match"条件下所有trial的平均反应时
    max_rt = max(rt, na.rm = TRUE),#每个被试在类似"circle_match"条件下所有trial的最大反应时
    min_rt = min(rt, na.rm = TRUE),#每个被试在类似"circle_match"条件下所有trial的最小反应时
    sd_rt=sd(rt, na.rm = TRUE), #每个被试在类似"circle_match"条件下所有trial的反应时的方差
    all_count=n(),#每个被试在每个条件的总trial数量
    row_count = sum(rt>=200 & rt <=1200, na.rm = TRUE),  #每个条件反应时符合条件的总数,舍弃按键太快和按键太慢的
    correct_count = sum(correct == 1 & rt>=200 & rt <=1200, na.rm = TRUE),
    acc = correct_count /all_count ,#计算每个被试在每个条件的正确率= 正确/总数
  )
print(ALT1_data)
print(describe(ALT1_data))
```

# 查看ALT1的匹配与不匹配的正确率和反应时的分布
```{r 按匹配与不匹配绘制acc和RT}
ALT1_data2 <- ALT1_data%>%
  group_by(conditionType,condition)%>%
  reframe(
     mean_rt= mean(avg_rt), #每个被试在该条件下的平均反应时（每个被试一个值avg_rt)的平均值
    se_rt=sd(avg_rt) / sqrt(length(avg_rt)), #每个被试在该条件下的平均反应时（avg_rt)的标准误
    mean_acc=mean(acc), #每个被试在该条件下的正确率（每个被试一个值acc)的平均值
    se_acc=sd(acc)/sqrt(length(acc))#每个被试在该条件下的正确率（acc)的标准误
)
print(ALT1_data2)
```

## ALT1各图形*匹配/不匹配的反应时
```{r bar_plot of rt in ALT1}
ALT1_plot_rt <- ALT1_data2%>%
  ggplot(., aes(x = condition, y = mean_rt, fill = conditionType)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  geom_errorbar(aes(ymin = mean_rt - se_rt, ymax = mean_rt + se_rt), position = position_dodge(width = 0.8), width = 0.25)+
  geom_text(
    aes(label = round(mean_rt)),  # Add labels rounded to the nearest integer
    position = position_dodge(width = 0.8),
    vjust = -0.8,  # Adjust vertical position of labels
    size = 3  # Adjust label size if needed
  )+
  scale_fill_grey(start = 0.3) +
  scale_y_continuous(limits = c(0, 900), breaks = seq(0, 900, 50), expand = c(0, 0)) +
 guides(fill = guide_legend(title = "Identity"))+
  theme_minimal()  +
  labs(
    x = "condition",
    y = "RT",
    title = "RT of ALT1 in Different condition",
    caption = "Error bars indicate a standard error"
  )  +
  theme(
    plot.title = element_text(size = 20,
                              face = "bold",
                              margin = margin(b = 35)),
    
    axis.line = element_line(color = "#3D4852"),
    axis.ticks = element_line(color = "#3D4852"),
    panel.grid.major.y = element_line(color = "#DAE1E7"),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.y = element_blank()
  )  
print(ALT1_plot_rt)
```

## ALT1各图形*匹配/不匹配的正确率
```{r bar_plot of acc in ALT1}
ALT1_plot_ACC <- ALT1_data2%>%
  ggplot(., aes(x = condition, y = mean_acc, fill = conditionType)) +
  geom_bar(stat = "identity", position = position_dodge(), na.rm = TRUE) +
  geom_errorbar(aes(ymin = mean_acc - se_acc, ymax = mean_acc + se_acc), position = position_dodge(width = 0.8), width = 0.25)+
  geom_text(
    aes(label = round(mean_acc, digits = 2)),  # Add labels rounded to the nearest integer
    position = position_dodge(width = 0.6),
    vjust = -0.8,  # Adjust vertical position of labels
    size = 3  # Adjust label size if needed
  )+
  scale_fill_grey(start = 0.3) +
  scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, 0.1),expand = c(0, 0.1)) +
 guides(fill = guide_legend(title = "Identity"))+
  theme_minimal()  +
  labs(
    x = "condition",
    y = "ACC",
    title = "ACC of ALT1 in Different condition",
    caption = "Error bars indicate a standard error"
  )  +
  theme(
    plot.title = element_text(size = 20,
                              face = "bold",
                              margin = margin(b = 35)),
    
    axis.line = element_line(color = "#3D4852"),
    axis.ticks = element_line(color = "#3D4852"),
    panel.grid.major.y = element_line(color = "#DAE1E7"),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.y = element_blank()
  )  
print(ALT1_plot_ACC)
```

## ALT1各图形*匹配/不匹配的反应时与正确率的雨云图
```{r 按匹配与不匹配绘制acc和RT}
acc_and_rt_plots <- function(data,output_file) {
  print(data)

# ACC plot
  acc_plot <- ggplot(data, aes(x = condition, y = acc, fill = conditionType, colour = conditionType)) +
    geom_flat_violin(position = position_nudge(x = .25, y = 0), adjust = 2, trim = FALSE, alpha = 0.5) +
    geom_point(position = position_jitter(width = .15), size = .25, alpha = 0.5) +
    geom_boxplot(aes(x = condition, y = acc), outlier.shape = NA, alpha = 0.5, width = .1, colour = "BLACK") +
    ylab('Acc') + xlab('conditionType') + coord_flip() +
    theme_cowplot() + guides(fill = FALSE, colour = FALSE) +
    scale_colour_brewer(palette = "Dark2") +
    scale_fill_brewer(palette = "Dark2") +
    ggtitle("Figure 1a: ACC of ALT1")+
  guides(fill = guide_legend(title = "condition"), colour = guide_legend(title = "condition"))

  # RT plot
  rt_plot <- ggplot(data, aes(x = condition, y = avg_rt, fill = conditionType, colour = conditionType)) +
    geom_flat_violin(position = position_nudge(x = .25, y = 0), adjust = 2, trim = FALSE, alpha = 0.5) +
    geom_point(position = position_jitter(width = .15), size = .25, alpha = 0.5) +
    geom_boxplot(aes(x = condition, y = avg_rt), outlier.shape = NA, alpha = 0.5, width = .1, colour = "BLACK") +
    ylab('RT') + xlab('conditionType') + coord_flip() +
    theme_cowplot() + guides(fill = FALSE, colour = FALSE) +
    scale_colour_brewer(palette = "Dark2") +
    scale_fill_brewer(palette = "Dark2") +
    ggtitle("Figure 1b: RT of ALT1")+
  guides(fill = guide_legend(title = "condition"), colour = guide_legend(title = "condition"))

  # Combine plots vertically
  final_plot <- acc_plot | rt_plot
   ggsave(output_file, final_plot, width = 10, height = 15)
  print(final_plot)
}


# 使用函数并传递ALT1_plot_phase_003作为参数
ALT1_plot <- acc_and_rt_plots(ALT1_data,"../../Data/all/ALT1_plot.png")

```

## ALT1各图形*匹配/不匹配的正确率的方差分析
```{r ALT1_ACC_ANOVA}
  ALT1_ACC <-ALT1_data%>% 
  #ungroup()%>%
  MANOVA(., dv = "acc", subID="ID",
       within=c("conditionType", "condition"),
       sph.correction="GG") %>%
    EMMEANS("conditionType", by = "condition") %>%
    EMMEANS("condition", by = "conditionType")

  print(ALT1_ACC)
```

## ALT1各图形*匹配/不匹配的反应时的方差分析
```{r ALT1_RT_ANOVA}
  ALT1_RT <-ALT1_data%>% 
  #ungroup()%>%
  MANOVA(., dv = "avg_rt", subID="ID",
       within=c("conditionType", "condition"),
       sph.correction="GG") %>%
    EMMEANS("conditionType", by = "condition") %>%
    EMMEANS("condition", by = "conditionType")


  print(ALT1_RT)
```

