---
title: "questionnaire"
output: word_document
date: "2024-01-20"
---

```{r setup, include=FALSE}
#合并day0到day2的问卷数据
day0t2_q<- merge(day0_all, day1_q_all, by = "ID", all = TRUE) %>%
  merge(day2_q_all, by = "ID", all = TRUE)%>%
  mutate(
    phq_al = rowSums(select(., starts_with("phq")), na.rm = TRUE),
    gad_al = rowSums(select(., starts_with("gad")), na.rm = TRUE),
    selfclarity_al = rowSums(select(., starts_with("selfclarity")), na.rm = TRUE),
    ses_al = rowSums(select(., starts_with("ses")), na.rm = TRUE),
    coreself_al =rowSums(select(., starts_with("coreself")), na.rm = TRUE),
    SGPS_al = rowSums(select(., starts_with("SGPS")), na.rm = TRUE),
    hsns_al = rowSums(select(., starts_with("hsns")), na.rm = TRUE),
    NPI_al = rowSums(select(., starts_with("NPI")), na.rm = TRUE),
    swb_al = rowSums(select(., starts_with("swb")), na.rm = TRUE),
    LOT_al = rowSums(select(., starts_with("LOT")), na.rm = TRUE),
    sde_al= rowSums(select(., starts_with("sde")), na.rm = TRUE),
    IM_al= rowSums(select(., starts_with("IM")), na.rm = TRUE),
    MorIden_al= rowSums(select(., starts_with("MorIden")), na.rm = TRUE),
    moralSeImag_al= rowSums(select(., starts_with("moralSeImag")), na.rm = TRUE),
    IPC_al = (rowSums(select(., starts_with("IPC")), na.rm = TRUE)+24)
  )%>%mutate(gad = case_when(
    gad_al >= 0 & gad_al <= 4 ~ "无",
    gad_al >= 5 & gad_al <= 9 ~ "轻度",
    gad_al >= 10 & gad_al <= 14 ~ "中度",
    gad_al >= 15 ~ "重度",
    TRUE ~ NA_character_
  ))%>%
   mutate(phq = case_when(
    phq_al >= 0 & phq_al <= 4 ~ "无",
    phq_al >= 5 & phq_al <= 9 ~ "轻度",
    phq_al >= 10 & phq_al <= 14 ~ "中度",
    phq_al >= 15 & phq_al <= 19 ~ "中重度",
     phq_al >= 20  ~ "重度",
    TRUE ~ NA_character_
  ))
  

```

```{r}
day3_q_all<-day3_q_all%>%
  mutate(
    phq_al = rowSums(select(., starts_with("phq")), na.rm = TRUE),
    gad_al = rowSums(select(., starts_with("gad")), na.rm = TRUE),
    selfclarity_al = rowSums(select(., starts_with("selfclarity")), na.rm = TRUE),
    ses_al = rowSums(select(., starts_with("ses")), na.rm = TRUE),
    coreself_al =rowSums(select(., starts_with("coreself")), na.rm = TRUE),
    SGPS_al = rowSums(select(., starts_with("SGPS")), na.rm = TRUE),
    hsns_al = rowSums(select(., starts_with("hsns")), na.rm = TRUE),
    NPI_al = rowSums(select(., starts_with("NPI")), na.rm = TRUE),
    swb_al = rowSums(select(., starts_with("swb")), na.rm = TRUE),
    LOT_al = rowSums(select(., starts_with("LOT")), na.rm = TRUE),
    sde_al= rowSums(select(., starts_with("sde")), na.rm = TRUE),
    IM_al= rowSums(select(., starts_with("IM")), na.rm = TRUE),
    MorIden_al= rowSums(select(., starts_with("MorIden")), na.rm = TRUE),
    moralSeImag_al= rowSums(select(., starts_with("moralSeImag")), na.rm = TRUE),
    IPC_al = (rowSums(select(., starts_with("IPC")), na.rm = TRUE)+24)
  )%>%mutate(gad = case_when(
    gad_al >= 0 & gad_al <= 4 ~ "无",
    gad_al >= 5 & gad_al <= 9 ~ "轻度",
    gad_al >= 10 & gad_al <= 14 ~ "中度",
    gad_al >= 15 ~ "重度",
    TRUE ~ NA_character_
  ))%>%
   mutate(phq = case_when(
    phq_al >= 0 & phq_al <= 4 ~ "无",
    phq_al >= 5 & phq_al <= 9 ~ "轻度",
    phq_al >= 10 & phq_al <= 14 ~ "中度",
    phq_al >= 15 & phq_al <= 19 ~ "中重度",
     phq_al >= 20  ~ "重度",
    TRUE ~ NA_character_
  ))
```

```{r}
plot_bar(day3_q_all)

```


```{r 计算前后测的皮尔逊积差相关，重测信度}

#选择要算重测信度的量表
questionnaires <- c("IPC_al", "LOT_al", "swb_al", "NPI_al", "hsns_al", "SGPS_al", "coreself_al", "ses_al", "selfclarity_al", "gad_al", "phq_al","MorIden_al","moralSeImag_al","sde_al","IM_al")

# 计算重测信度

# 存储计算的重测信度
reliabilities <- data.frame(questionnaire = character(0), reliability = numeric(0))

for (questionnaire in questionnaires) {
  # 选择两次测量的数据，for循环
  data1 <- day0t2_q [, c("ID", questionnaire)]
  data2 <- day3_q_all [, c("ID", questionnaire)]
  
  # 合并数据框
  combined_data <- merge(data1, data2, by = "ID", suffixes = c("_1", "_2"))
  
  # 计算重测信度，利用pearson积差相关
  reliability <- cor(combined_data[, paste(questionnaire, "_1", sep = "")], combined_data[, paste(questionnaire, "_2", sep = "")],method = "pearson", use = "pairwise")
  
  # 存储结果
  reliabilities <- rbind(reliabilities, data.frame(questionnaire = questionnaire, reliability = reliability))
}

# 输出重测信度
print(reliabilities)

```


```{r bruceR对day3的各分量表总分以及领域自尊5维度的相关热图}
day3_q_all<-day3_q_all%>%
  rename(ability_rating =domain_rating_1,
         physical_attraction=domain_rating_2,
         material_wealth=domain_rating_3, 
         social_ability=domain_rating_4,
         moral_rating=domain_rating_5)
day3_q_all%>%
  select(.,ends_with("_al"),ability_rating,physical_attraction,material_wealth, social_ability,moral_rating)%>%
bruceR::Corr(.,
  method = "spearman",#"pearson" (default), "spearman", or "kendall".
  p.adjust = "none",#"none", "fdr", "holm", "bonferroni
  all.as.numeric = TRUE,
  digits = 2,
  file = NULL,#File name of MS Word (.doc).
  plot = TRUE,
  plot.r.size = 4,
  plot.colors = NULL,
  plot.file = NULL,
  plot.width =20,
  plot.height =20,
  plot.dpi = 500)
```

# 判断是否适合EFA
```{r}

day3_q_cor<-day3_q_all%>%
  #select(-ends_with("_al"),-ID,-X,-ParticipantID,)%>%
  select(.,ends_with("_al"),ability_rating,physical_attraction,material_wealth, social_ability,moral_rating)

 cortest.bartlett(day3_q_cor)
KMO(day3_q_cor)
```
# 确定因子数-------- Bayesian Information Criteria (BIC) is a criterion for model selection
```{r}
factor.num = fa.parallel(day3_q_cor,fa='both',n.iter = 100,
  main='我的碎石图')
```

You can also embed plots, for example:

```{r}

day3_q_fa<-day3_q_cor%>%fa(.,fm="pa",nfactor=3,rotate="promax")%>%
#fm因素萃取法--vaiirmax最大变异法，nfacto提取因子数，rotate转轴方法
print(.,cut=0.35)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
```{r}
day3_q_cor%>%fa(.,fm="pa",nfactor=3,rotate="promax")%>%    #performed using maximum likelihood estimation，Factor scores were estimated using the tenBerge
fa.diagram(fit1,cut=0.35,sort=TRUE,digits=2)
```


# 因子得分

```{r}

day3_q_fa<-day3_q_cor%>%fa(.,fm="pa",nfactor=3,rotate="promax")
#fm因素萃取法--vaiirmax最大变异法，nfacto提取因子数，rotate转轴方法
print(day3_q_fa,cut=0.35)


```



```{r}
factor.scores(day3_q_cor,f=day3_q_fa)
```




```{r}
iclust(day3_q_cor)
```

